'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { stripTypeScriptTypes } = require('node:module');
// Run the pure store with a React subscription stub and a controllable clock.
let source = fs.readFileSync(path.join(__dirname, '../ThirdFloorDirector.ts'), 'utf8');
source = source.replace('import { useSyncExternalStore } from "react";', 'const useSyncExternalStore = (...args: unknown[]) => args;');
source = stripTypeScriptTypes(source).replace(/export const /g, 'const ');
source += '\nmodule.exports = { thirdFloorDirector };';
const timers = new Map();
let timer = 0;
const context = { module: { exports: {} }, setTimeout: fn => { timers.set(++timer, fn); return timer; }, clearTimeout: id => timers.delete(id) };
vm.runInNewContext(source, context);
const director = context.module.exports.thirdFloorDirector;
const event = { id: 'run-1-start', source: 'n8n', floorId: 'dev-third', agentId: 'n8n-reviewer', runId: 'run-1', sequence: 1, status: 'workflow.running' };
const frame = event => ({ type: 'event', event: 'sofia.ops', payload: event });
assert.equal(director.ingest({ type: 'event', event: 'agent', payload: {} }), false);
assert.equal(director.ingest(frame({ ...event, floorId: 'audit-second' })), true);
assert.equal(Object.keys(director.getSnapshot()).length, 0);
let notified = 0;
const unsubscribe = director.subscribe(() => ++notified);
director.ingest(frame({ ...event, patient: 'must drop', token: 'must drop' }));
const first = director.getSnapshot();
assert.equal(first[event.agentId].status, 'workflow.running');
assert.equal(first[event.agentId].patient, undefined);
director.ingest(frame(event));
assert.equal(director.getSnapshot(), first);
assert.equal(notified, 1);
director.ingest(frame({ ...event, id: 'done', sequence: 2, status: 'workflow.completed' }));
assert.equal(director.getSnapshot()[event.agentId].status, 'workflow.completed');
director.ingest(frame({ ...event, id: 'stale', sequence: 1 }));
assert.equal(director.getSnapshot()[event.agentId].status, 'workflow.completed');
director.ingest(frame({ ...event, id: 'restart', sequence: 3 }));
assert.equal(director.getSnapshot()[event.agentId].status, 'workflow.completed');
director.ingest(frame({ ...event, runId: 'run-2', id: 'run-2-start' }));
director.ingest(frame({ ...event, id: 'old-run-failed', sequence: 4, status: 'workflow.failed' }));
assert.equal(director.getSnapshot()[event.agentId].runId, 'run-2');
assert.equal(director.getSnapshot()[event.agentId].status, 'workflow.running');
for (const fn of [...timers.values()]) fn();
assert.equal(Object.keys(director.getSnapshot()).length, 0);
director.preview('workflow.running');
assert.equal(director.getSnapshot().main.status, 'workflow.running');
director.preview('workflow.failed');
assert.equal(director.getSnapshot().main.status, 'workflow.failed');
assert.equal(director.preview('invalid'), false);
director.ingest(frame({ ...event, agentId: 'main', runId: 'real-run', id: 'real-main' }));
assert.equal(director.getSnapshot().main.runId, 'real-run');
director.preview(null);
assert.equal(director.getSnapshot().main.runId, 'real-run');
for (const fn of [...timers.values()]) fn();
assert.equal(Object.keys(director.getSnapshot()).length, 0);
director.preview('workflow.completed');
for (const fn of [...timers.values()]) fn();
assert.equal(Object.keys(director.getSnapshot()).length, 0);
unsubscribe();
console.log('PASS: third-floor scope, metadata privacy, duplicate/old events, terminal states, cross-run concurrency and timer release');
